### ISSUE TITLE
Lodash

### ISSUE THREAD

**Issue by tomitrescak** [dataflows/meteor-typescript-utils#1]
Hi, first thanks for the awesome package! I really enjoy what you've done!

I have a question, if it possible to get rid of lodash in this package? It's conflicting with underscore all over the place ;)

**Comment by marekrogala** [comment]
Hi! Glad to hear that:) 

We're using lodash internally, so that's why it was here in the first place. However, underscore should be enough here. I'll change this soon.

**Comment by tomitrescak** [comment]
That was fast! Thanks. Will wait for the new version ;) 

Can I have two off topic questions? Sorry ...
1. In your tslint.json you banned _.extend .. why?
2. You managed to compile everything with noExplicitAny .. but .d.ts file related to meteor are full of it. Did you customise the meteor.d.ts file? If so ... how do you plan to maintain it towards latest API?

**Comment by marekrogala** [comment]
I've published a new version which no longer depends on lodash.

Regarding your questions:
1. Of course this is just an example project so anyone can use their own settings:) In most cases you can have a dedicated method for which does a particular operation on objects of given types instead of using `_.extend`. We think you end up with a better design. We haven't found any situation where `_.extend` would be justified, and banning it encourages us not to take shortcuts. But I'm definitely interested if you see any scenario in which it would be beneficial to use `_.extend`:)
2. Yes, the .d.ts file contained in this repository is a custom one. `noImplicitAny` (and the 'no any' option in linter) are crucial since `any` is extremely harmful. Custom d.ts was the most straightforward way for this to compile, but eventually it will be a challenge to maintain it separately. My plan is to make a contribution to the most popular meteor.d.ts which adds all missing anys, any other ideas?

**Comment by tomitrescak** [comment]
Marek, thanks for your answer. Am a long life js programmer, just getting used to typescript, and while it feels like coming to army where "alles im ordnung must sein", it also feel good to leave the realms of chaos in my big projects.

Concerning the extend, I was using it to add methods to modules across the files. To have the opportunity of compiling to separate files to facilitate the debug I play Don Quixote and I create modules in a following way:

``` javascript
module MyModule {
...
}

// if module is defined across several files
_.extend(this.MyModule = this.MyModule ? this.MyModule : {}, MyModule);

// or if module exists only in one file we export in into global namespace
this.MyModule = MyModule;
```

This allows me to keep multiple files and not to compile to single file. But it is of course prone to load order issues, which I have to solve lexicographically by manually ordering the files, but so far that has not been a major issue.

What do you think?
